### PR TITLE
Added Matomo tracking pixel

### PR DESCRIPTION
**Pull request by hendrikschneider**
implemented #21

### CODE REVIEW

**Comment by burner1024** [comment]
I believe `<img src` is missing forward slashes before the url.

**Comment by burner1024** [comment]
And it probably should be wrapped in noscript, to avoid double-logging, like the last example in the [doc](https://matomo.org/faq/how-to/faq_176/):
```
<noscript><p><img src="http://matomo.example.org/matomo.php?idsite=1&rec=1" style="border:0" alt="" /></p></noscript>
```

**Comment by burner1024** [comment]
... and img should probably go into body, rather than head.

**Comment by saschazelzer** [comment]
I run into those issues as well, would be great to see them fixed. Thanks for the plugin!

**Pull request merged**
